# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f066a875c36693a0788307bf942a69c0b241eb55b6d8c80cbabed02bb46e34cacb3f948ab402ff5c613d2bca125045165947563041006353a8d3ab6ada9817

test:
  secret_key_base: acddede1b5b08263d5cb91b8ed345b695a480db818077d708dbb9acd347e52cbc30314d1588fc6fd2aae17dea380556735e210fca33dae3026da3edaa949c9ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
